/**
 * Scenario Category Enum
 * Categories for grouping AI generation scenarios
 */

export enum ScenarioCategory {
  TIME_TRAVEL = "time_travel",
  FAMILY = "family",
  INTIMATE = "intimate",
  WEDDING = "wedding",
  TRAVEL = "travel",
  CULTURAL = "cultural",
  HISTORICAL = "historical",
  FANTASY = "fantasy",
  SCI_FI = "sci_fi",
  ARTISTIC = "artistic",
  CINEMATIC = "cinematic",
  PERFORMANCE = "performance",
  CREATIVE = "creative",
  FASHION = "fashion",
  FESTIVAL = "festival",
  HOBBIES = "hobbies",
  SPORTS = "sports",
  EXTREME = "extreme",
  GAMING = "gaming",
  CAREER = "career",
  EDUCATION = "education",
  LIFESTYLE = "lifestyle",
  LUXURY = "luxury",
  CULINARY = "culinary",
  SEASONAL = "seasonal",
  ANIMALS = "animals",
  CELEBRATIONS = "celebrations",
  HOME_LIFE = "home_life",
  WELLNESS = "wellness",
  BUCKET_LIST = "bucket_list",
  SOCIAL_MEDIA = "social_media",
  MYTHOLOGY = "mythology",
  FUTURE_TECH = "future_tech",
  ACTION_STEALTH = "action_stealth",
  ECOLOGY = "ecology",
  NOSTALGIA = "nostalgia",
  MYSTICAL = "mystical",
  SUPERHEROES = "superheroes",
  VILLAINOUS = "villainous",
  ELITE = "elite",
  GOTHIC = "gothic",
  CONNECTION = "connection",
  DAILY_ESSENCE = "daily_essence",
  MOVIE_LEGENDS = "movie_legends",
  ICONIC_MOMENTS = "iconic_moments",
  FOLKLORE = "folklore",
  MUSIC = "music",
  STEAMPUNK = "steampunk",
  ADVENTURE = "adventure",
  AFFECTION = "affection",
  ROMANTIC_KISSES = "romantic_kisses",
  SULTRY = "sultry",
  STOLEN_MOMENTS = "stolen_moments",
  URBAN_NIGHTS = "urban_nights",
  VINTAGE_SUMMER = "vintage_summer",
  ART_STUDIO = "art_studio",
  DARK_ACADEMIA = "dark_academia",
  CASINO = "casino",
  POST_APOCALYPTIC = "post_apocalyptic",
  RETRO_ARCADE = "retro_arcade",
  COZY_PLUSH = "cozy_plush",
  PIRATE_ERA = "pirate_era",
  SAMURAI = "samurai",
  SURREAL_DREAMS = "surreal_dreams",
  MAGICAL_REALISM = "magical_realism",
  VINTAGE_CIRCUS = "vintage_circus",
  ELEMENTAL = "elemental",
  SPEED_DEMONS = "speed_demons",
  UNDERWATER = "underwater",
  ARABIAN_NIGHTS = "arabian_nights",
  PREHISTORIC = "prehistoric",
}
